name: amma_hospital_app
description: An appointment booking app for Amma Hospital.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  retrofit_generator: ^7.0.8
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.6
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
